apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: hnwb4hiq7-nodejs
  janus-idp.io/tekton: hnwb4hiq7-nodejs
  backstage.io/kubernetes-id: hnwb4hiq7-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hnwb4hiq7-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
